### ISSUE TITLE
[CRASH] ShadersV2 imports non-existent shaders

### ISSUE THREAD

**Issue by StartsMercury** [Shfloop/SimplyShaders#1]
Game crashes when enabling shaders with `ShadersV2` selected when `ShadersV1` is absent.

## Details

Two shaders, `chunk.frag.glsl` and `shadowpass.vert.glsl`, are importing from path `ShadersV1/distort.glsl` which will cause a crash if the said path is non-existent.

## Workaround

Copy `ShadersV2` and name it `ShadersV1`.

## Logs

```js
[INFO] [Cosmic Reach/GameAssetLoader]: Loading shaders/ShadersV1/distort.glsl from mods folder
[INFO] [Cosmic Reach/GameAssetLoader]: Loading shaders/ShadersV1/settings.glsl from mods folder
[INFO] [Cosmic Reach/rendering.shaders.GameShader]: Compiling shader(InternalShader/internal.shadowpass.vert.glsl, InternalShader/internal.shadowpass.frag.glsl)...
[INFO] [Cosmic Reach/rendering.shaders.GameShader]: Loaded uniform: GL_SAMPLER_BUFFER texBuffer at location=0
[INFO] [Cosmic Reach/rendering.shaders.GameShader]: Loaded uniform: GL_FLOAT_MAT4 u_modelMat at location=2
[INFO] [Cosmic Reach/rendering.shaders.GameShader]: Loaded uniform: GL_FLOAT_MAT4 u_projViewTrans at location=1
[INFO] [Cosmic Reach/rendering.shaders.GameShader]: Loaded uniform: GL_SAMPLER_2D texDiffuse at location=3
[INFO] [Cosmic Reach/rendering.shaders.GameShader]:
[INFO] [Cosmic Reach/GameAssetLoader]: Loading shaders/ShadersV2/distort.glsl from jar
[SEVERE] [java.lang.Throwable]: java.lang.RuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: File not found: shaders\ShadersV2\distort.glsl (Internal)
[SEVERE] [java.lang.Throwable]:  at com.shfloop.simply_shaders.ShaderSelectionMenu.applyShaderPackSelection(ShaderSelectionMenu.java:279)
[SEVERE] [java.lang.Throwable]:  at com.shfloop.simply_shaders.ShaderSelectionMenu$6.onClick(ShaderSelectionMenu.java:224)
[SEVERE] [java.lang.Throwable]:  at finalforeach.cosmicreach.ui.UIElement.drawBackground(UIElement.java:145)
[SEVERE] [java.lang.Throwable]:  at finalforeach.cosmicreach.gamestates.GameState.drawUIElements(GameState.java:121)
[SEVERE] [java.lang.Throwable]:  at com.shfloop.simply_shaders.ShaderSelectionMenu.render(ShaderSelectionMenu.java:312)
[SEVERE] [java.lang.Throwable]:  at finalforeach.cosmicreach.BlockGame.render(BlockGame.java:132)
[SEVERE] [java.lang.Throwable]:  at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
[SEVERE] [java.lang.Throwable]:  at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
[SEVERE] [java.lang.Throwable]:  at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
[SEVERE] [java.lang.Throwable]:  at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.createApplication(Lwjgl3Launcher.java:104)
[SEVERE] [java.lang.Throwable]:  at finalforeach.cosmicreach.lwjgl3.Lwjgl3Launcher.main(Lwjgl3Launcher.java:92)
[SEVERE] [java.lang.Throwable]:  at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[SEVERE] [java.lang.Throwable]:  at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[SEVERE] [java.lang.Throwable]:  at dev.crmodders.cosmicquilt.loader.CosmicGameProvider.launch(CosmicGameProvider.java:274)
[SEVERE] [java.lang.Throwable]:  at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
[SEVERE] [java.lang.Throwable]:  at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
[SEVERE] [java.lang.Throwable]: Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: shaders\ShadersV2\distort.glsl (Internal)
[SEVERE] [java.lang.Throwable]:  at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:142)
[SEVERE] [java.lang.Throwable]:  at com.badlogic.gdx.files.FileHandle.length(FileHandle.java:641)
[SEVERE] [java.lang.Throwable]:  at com.badlogic.gdx.files.FileHandle.estimateLength(FileHandle.java:239)
[SEVERE] [java.lang.Throwable]:  at com.badlogic.gdx.files.FileHandle.readString(FileHandle.java:204)
[SEVERE] [java.lang.Throwable]:  at com.badlogic.gdx.files.FileHandle.readString(FileHandle.java:197)
[SEVERE] [java.lang.Throwable]:  at finalforeach.cosmicreach.rendering.shaders.GameShader.loadShaderFile(GameShader.java:77)
[SEVERE] [java.lang.Throwable]:  at finalforeach.cosmicreach.rendering.shaders.GameShader.loadShaderFile(GameShader.java:114)
[SEVERE] [java.lang.Throwable]:  at finalforeach.cosmicreach.rendering.shaders.GameShader.reload(GameShader.java:210)
[SEVERE] [java.lang.Throwable]:  at finalforeach.cosmicreach.rendering.shaders.GameShader.reloadAllShaders(GameShader.java:48)
[SEVERE] [java.lang.Throwable]:  at com.shfloop.simply_shaders.Shadows.turnShadowsOn(Shadows.java:109)
[SEVERE] [java.lang.Throwable]:  at com.shfloop.simply_shaders.ShaderSelectionMenu.applyShaderPackSelection(ShaderSelectionMenu.java:276)
[SEVERE] [java.lang.Throwable]:  ... 15 more
```

**Comment by Shfloop** [comment]
Fixed with shadersV3
